;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	indent-for-tab-command
	keyboard-escape-quit
	org-beginning-of-line
	org-delete-char
	org-end-of-line
	))

(setq mc/cmds-to-run-once
      '(
	counsel-M-x
	isearch-forward-regexp
	isearch-printing-char
	isearch-repeat-forward
	org-self-insert-command
	))
